### ISSUE TITLE
Nice work, is there more docs to this?

### ISSUE THREAD

**Issue by Schizo** [jpdante/UE4-JoyConDriver#1]
Just found this repo by coincidence, is there more information? Do you need to have a device driver installed to use it?

**Comment by jpdante** [comment]
> Is there more information?

Of course, I can write a little documentation for the repository in a few hours.

> Do you need to have a device driver installed to use it?

No, the driver for JoyCons is already part of the plugin, the only thing needed is to synchronize a JoyCon with bluetooth on Windows and call the plugin functions via Blueprint or C++.

But keep in mind that the project is still in alpha, so there may be some crashes.
