### ISSUE TITLE
'Axis1D' is not a member of 'FKeyDetails'

### ISSUE THREAD

**Issue by noubuddy** [jpdante/UE4-JoyConDriver#10]
Cannot run the project with this plugin due to compilation error - JoyConInput.cpp: [C2039] 'Axis1D': is not a member of 'FKeyDetails'
Am I supposed to add 'Axis1D' option to FKeyDetails enum manually or what?
![Screenshot 2023-03-16 151122](https://user-images.githubusercontent.com/85153179/225627468-73492985-1cec-4918-adc8-ca7f04e1a576.png)

**Comment by jpdante** [comment]
Hi, could you provide more information?
Operational System, Unreal Version, IDE/Compiler.

**Comment by noubuddy** [comment]
OS: Windows 11
Unreal Version: 4.25
IDE: Jetbrains Rider 2022.1.2
Compiler: Microsoft Visual C++ compiler 
(I don't really know how can I figure out which compiler is there using, but google says just that Jetbrains Rider uses 'Microsoft Visual C++ compiler')

**Comment by noubuddy** [comment]
Well, I basically added 'Axis1D' to 'FKeyDetails' manually, recompiled the Engine and it all works now.

UPD: Adding Axis1D to FKeyDetails was not a correct solution. Use FloatAxis instead is a right one.
