### ISSUE TITLE
modificar o accelerometer

### ISSUE THREAD

**Issue by miltonalmeida** [jpdante/UE4-JoyConDriver#6]
não é um bug mas uma pergunta que estou tentado descobrir como eu não conheço muito e estou aprendendo unreal você sabe como eu posso modificar(se é possível via blueprint) as variáveis do acelerômetro, giroscópio ou eu tenho que modificar via código, exemplo quando eu conecto os joy con as variáveis deles começam meio que em uma posição diferente e gostaria de modificar isso para quando eu iniciar poder seta a variável.

**Comment by jpdante** [comment]
Olá, infelizmente o joycon/driver não permite alterar a posição inicial do controle já que essa posição é apenas estipulada com base nos dados que o controle prove, eu suponho que o que você deseja seja aplicar um offset no acelerometro, giroscópio ou IMU. Aplicando um offset nos valores eu acredito que os seus problemas possam ser resolvidos.
